[project]
name = "chagas-ecg-net"
version = "0.1.0"
description = ""
authors = [
    {name = "Matheus Fellet", email = "matheusmfellet@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "torch>=2.11.0,<3.0.0",
    "torchvision>=0.26.0,<0.27.0",
    "torchaudio>=2.11.0,<3.0.0",
    "mlflow==3.12.0",
    "scikit-learn>=1.8.0,<2.0.0",
    "fastapi>=0.135.3,<0.136.0",
    "uvicorn>=0.44.0,<0.45.0",
    "pydantic>=2.13.0,<3.0.0",
    "pydantic-settings>=2.14.1,<3.0.0",
    "prometheus-client>=0.25.0,<0.26.0",
    "pywavelets>=1.9.0,<2.0.0",
    "ptwt>=1.0.1,<2.0.0",
    "einops>=0.8.2,<0.9.0",
    "h5py>=3.16.0,<4.0.0",
    "wfdb>=4.3.1,<5.0.0",
    "python-multipart>=0.0.29,<0.0.30",
    "aiofiles>=24.0.0,<25.0.0"
]

[project.optional-dependencies]
dev = [
    "hydra-core>=1.3.2,<2.0.0",
    "omegaconf>=2.3.0,<3.0.0",
    "evidently>=0.7.21,<0.8.0",
    "tensorboard>=2.20.0,<3.0.0",
    "torchinfo>=1.8.0,<2.0.0",
    "pytest>=9.0.3,<10.0.0",
    "httpx>=0.28.1,<0.29.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[build-system]
requires = ["setuptools>=68.0.0"]
build-backend = "setuptools.build_meta"